DROP TABLE IF EXISTS fields;

DROP TABLE IF EXISTS advertisement_field;

DROP TABLE IF EXISTS candidates;

DROP TABLE IF EXISTS reviews;

DROP TABLE IF EXISTS advertisements;

DROP TABLE IF EXISTS categories;

DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS ROLE;

DROP TYPE IF EXISTS ADSTATUS;

DROP EXTENSION IF EXISTS CITEXT;

DROP EXTENSION IF EXISTS "uuid-ossp";
