// Code generated by mockery v2.20.0. DO NOT EDIT.

package usermock

import (
	context "context"
	user "go-api/internal/core/user"

	mock "github.com/stretchr/testify/mock"

	utils "go-api/pkg/utils"

	uuid "github.com/google/uuid"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, userID
func (_m *UseCase) Delete(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, userID
func (_m *UseCase) GetByID(ctx context.Context, userID uuid.UUID) (*user.Model, error) {
	ret := _m.Called(ctx, userID)

	var r0 *user.Model
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*user.Model, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *user.Model); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.Model)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: ctx, pq
func (_m *UseCase) GetUsers(ctx context.Context, pq *utils.PaginationQuery) (*user.List, error) {
	ret := _m.Called(ctx, pq)

	var r0 *user.List
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *utils.PaginationQuery) (*user.List, error)); ok {
		return rf(ctx, pq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *utils.PaginationQuery) *user.List); ok {
		r0 = rf(ctx, pq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.List)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *utils.PaginationQuery) error); ok {
		r1 = rf(ctx, pq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *UseCase) Login(ctx context.Context, email string, password string) (*user.Token, error) {
	ret := _m.Called(ctx, email, password)

	var r0 *user.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*user.Token, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *user.Token); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, _a1
func (_m *UseCase) Register(ctx context.Context, _a1 *user.Model) (*user.Token, error) {
	ret := _m.Called(ctx, _a1)

	var r0 *user.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.Model) (*user.Token, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.Model) *user.Token); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.Model) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *UseCase) Update(ctx context.Context, _a1 *user.Model) (*user.Model, error) {
	ret := _m.Called(ctx, _a1)

	var r0 *user.Model
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.Model) (*user.Model, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.Model) *user.Model); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.Model)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.Model) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUseCase(t mockConstructorTestingTNewUseCase) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
